# Generates the .clangd that makes the editor agree with the build.
#
# compile_commands.json names em++ as the compiler, and clangd cannot drive it:
# em++ is a Python wrapper, not a clang. clangd gives up and parses with the
# host defaults, so `__EMSCRIPTEN__` is undefined and every #include resolves
# against the host SDK instead of the Emscripten sysroot. The build is fine;
# only the editor is wrong, which is the worst kind of wrong.
#
# The fix is to name the clang that em++ actually invokes, plus the flags it
# actually adds. `em++ --cflags` is the source of truth for those, so this can
# never drift from the SDK pinned in .emscripten-version.
#
# The result is generated rather than committed because it names whichever SDK
# and build directory this machine resolved. Paths under the source tree are
# written relative, so a generated file has nothing machine-specific in it.

option(ARENA_WRITE_CLANGD_CONFIG
       "Write .clangd at configure time so clangd sees Emscripten's flags" ON)

set(ARENA_CLANGD_NATIVE_PATHS "tests;testing" CACHE STRING
    "Directories under the project root that clangd should read from the native \
build instead: they are compiled for the host, not for WASM")

# Line 1 of anything we wrote. A .clangd without it belongs to the user, and
# clobbering someone's own editor config is not ours to do.
set(ARENA_CLANGD_MARKER
    "# Generated by cmake/ClangdConfig.cmake. Edits are lost on reconfigure.")

# Writes ${CMAKE_SOURCE_DIR}/.clangd. No-op unless configuring with Emscripten,
# since the flags being captured are Emscripten's.
function(arena_write_clangd_config)
  if(NOT ARENA_WRITE_CLANGD_CONFIG OR NOT EMSCRIPTEN)
    return()
  endif()

  set(out "${CMAKE_SOURCE_DIR}/.clangd")
  if(EXISTS "${out}")
    file(STRINGS "${out}" first_line LIMIT_COUNT 1)
    if(NOT first_line STREQUAL ARENA_CLANGD_MARKER)
      message(STATUS
        "clangd: leaving your own ${out} alone "
        "(-DARENA_WRITE_CLANGD_CONFIG=OFF to stop looking)")
      return()
    endif()
  endif()

  execute_process(
    COMMAND "${CMAKE_CXX_COMPILER}" --cflags
    OUTPUT_VARIABLE cflags
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_VARIABLE cflags_error
    RESULT_VARIABLE cflags_result
  )
  if(NOT cflags_result EQUAL 0)
    message(WARNING
      "clangd: '${CMAKE_CXX_COMPILER} --cflags' failed, skipping .clangd:\n"
      "${cflags_error}")
    return()
  endif()

  # Where the SDK sits decides whether the file can be committed. `npm run
  # setup` puts it under third_party/, and a path inside the source tree can be
  # written relative, keeping this machine's home directory out of the file. An
  # SDK picked up from $EMSDK is somewhere else entirely and has to stay
  # absolute -- but then the file is nobody else's to reuse anyway.
  #
  # The base is the *build* directory, not this file's: relative paths in
  # `Compiler:` and in `Add:` are resolved against the compile command's
  # directory. Only `CompilationDatabase:` is relative to .clangd.
  set(source_prefix "${CMAKE_SOURCE_DIR}/")
  set(portable_prefix "${source_prefix}")
  string(FIND "${CMAKE_BINARY_DIR}/" "${source_prefix}" binary_dir_is_inside)
  if(binary_dir_is_inside EQUAL 0)
    file(RELATIVE_PATH portable_prefix "${CMAKE_BINARY_DIR}" "${CMAKE_SOURCE_DIR}")
    # CMake is inconsistent about a trailing slash here, and an in-source build
    # relativises to the empty string.
    string(REGEX REPLACE "/+$" "" portable_prefix "${portable_prefix}")
    if(portable_prefix STREQUAL "")
      set(portable_prefix ".")
    endif()
    string(APPEND portable_prefix "/")
  endif()

  separate_arguments(flags UNIX_COMMAND "${cflags}")
  set(add_block "")
  foreach(flag IN LISTS flags)
    string(REPLACE "${source_prefix}" "${portable_prefix}" flag "${flag}")
    string(REPLACE "\\" "\\\\" flag "${flag}")
    string(REPLACE "\"" "\\\"" flag "${flag}")
    string(APPEND add_block "    - \"${flag}\"\n")
  endforeach()

  # em++ lives at <sdk>/upstream/emscripten/em++; the clang it drives is at
  # <sdk>/upstream/bin/clang++. Naming it also gets clangd the matching builtin
  # headers, which its own bundled resource directory would not supply.
  get_filename_component(emscripten_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
  get_filename_component(llvm_root "${emscripten_dir}/.." REALPATH)
  set(compiler_line "")
  if(EXISTS "${llvm_root}/bin/clang++")
    set(clangxx "${llvm_root}/bin/clang++")
    string(REPLACE "${source_prefix}" "${portable_prefix}" clangxx "${clangxx}")
    set(compiler_line "  Compiler: ${clangxx}\n")
  endif()

  # Whichever WASM preset was configured last wins, so `wasm-debug` points the
  # editor at build/wasm-debug rather than at a stale build/wasm.
  file(RELATIVE_PATH wasm_db "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}")

  # clangd matches these against the path relative to the .clangd, not against
  # the absolute path.
  set(native_regexes "")
  foreach(dir IN LISTS ARENA_CLANGD_NATIVE_PATHS)
    if(native_regexes)
      string(APPEND native_regexes ", ")
    endif()
    string(APPEND native_regexes "\"${dir}/.*\"")
  endforeach()

  set(wasm_condition "")
  set(native_fragment "")
  if(native_regexes)
    set(wasm_condition "If:\n  PathExclude: [${native_regexes}]\n")
    # Host-compiled sources need the opposite of everything above: no sysroot,
    # no wasm triple, and the include paths of the `native` preset (GoogleTest
    # among them). A second fragment is the only way to say that, because Add:
    # accumulates across fragments and cannot be taken back.
    set(native_fragment
        "---\n"
        "If:\n  PathMatch: [${native_regexes}]\n"
        "CompileFlags:\n  CompilationDatabase: build/native\n")
    string(JOIN "" native_fragment ${native_fragment})
  endif()

  file(WRITE "${out}"
    "${ARENA_CLANGD_MARKER}\n"
    "# Run a WASM configure (`cmake --preset wasm`) to refresh it; see\n"
    "# cmake/ClangdConfig.cmake for why em++ alone is not enough for clangd.\n"
    "\n"
    "${wasm_condition}"
    "CompileFlags:\n"
    "  CompilationDatabase: ${wasm_db}\n"
    "${compiler_line}"
    "  Add:\n"
    "${add_block}"
    "${native_fragment}"
  )
  message(STATUS "clangd: wrote ${out} (database: ${wasm_db})")
endfunction()
